services:
  - type: web
    name: power-ms-trading-pro-backend
    env: python
    region: frankfurt  # أو أي منطقة قريبة منك
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: PORT
        value: 10000
      - key: BINANCE_API_KEY
        sync: false  # سيطلب منك إدخاله يدوياً
      - key: BINANCE_API_SECRET
        sync: false  # سيطلب منك إدخاله يدوياً
      - key: DATABASE_URL
        fromDatabase:
          name: power-ms-trading-db
          property: connectionString
      - key: PYTHON_SETUPTOOLS_VERSION
        value: "65.5.1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"

databases:
  - name: power-ms-trading-db
    databaseName: power_ms_trading
    user: power_ms_user
    plan: free  # يمكنك تغيير الخطة لاحقاً إذا احتجت
